name: plant
channels:
  - pyg
  - conda-forge
  - huggingface
  - anaconda
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=0.13.0=py37h06a4308_0
  - aiohttp=3.7.4=py37h27cfd23_1
  - async-timeout=3.0.1=py37h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.4.26=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.5=py37h261ae71_0
  - click=8.0.1=pyhd3eb1b0_0
  - cryptography=3.4.7=py37hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.4.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - giflib=5.2.1=h7b6447c_0
  - git=2.23.0=pl526hacde149_0
  - glib=2.68.2=h36276a3_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.36.1=py37h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - huggingface_hub=0.0.17=py_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib_metadata=1.5.0=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37h2531618_0
  - krb5=1.18.2=h173b8e3_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libjpeg-turbo=2.1.0=h7f98852_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=py37h06a4308_0
  - matplotlib=3.3.4=py37h06a4308_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - multidict=5.1.0=py37h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.5.1=pyhd3eb1b0_0
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py37h2d18471_0
  - numpy-base=1.20.2=py37hfae3a4d_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.4=py37h8c16a72_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - pip=21.1.2=py37h06a4308_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.9.0=py3.7_cuda10.2_cudnn7.6.5_0
  - pytorch-scatter=2.0.9=py37_torch_1.9.0_cu102
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyyaml=5.4.1=py37h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - regex=2021.11.2=py37h7f8727e_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - sacremoses=master=py_0
  - scikit-image=0.18.1=py37ha9443f7_0
  - scipy=1.6.2=py37had2a1c9_1
  - seaborn=0.11.2=pyhd3eb1b0_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard=2.5.0=py_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tifffile=2020.10.1=py37hdd07704_2
  - timm=0.4.12=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!152.20180717=h14c3975_1001
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py37h27cfd23_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - antlr4-python3-runtime==4.8
    - beartype==0.9.1
    - colorama==0.4.5
    - dictor==0.1.7
    - diskcache==5.3.0
    - docker-pycreds==0.4.0
    - einops==0.4.0
    - ephem==4.0.0.2
    - filterpy==1.4.5
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - hydra-core==1.1.1
    - imageio-ffmpeg==0.4.4
    - importlib-metadata==4.6.1
    - importlib-resources==5.4.0
    - joblib==1.0.1
    # - mmcv-full==1.4.1
    # - mmdet==2.19.1
    - munkres==1.1.4
    - omegaconf==2.1.1
    - opencv-python==4.5.2.54
    - pathtools==0.1.2
    - pillow==8.3.2
    - promise==2.3
    - psutil==5.8.0
    - py-trees==0.8.3
    - pycocotools==2.0.3
    - pydeprecate==0.3.1
    - pydot==1.4.2
    - pygame==2.0.1
    - pygments==2.10.0
    - pytorch-lightning==1.5.10
    - rdp==0.8
    - scikit-learn==1.0
    - setuptools==59.5.0
    - shapely==1.7.1
    - shortuuid==1.0.1
    - slurm-gpustat==0.0.12
    - smmap==4.0.0
    - tabulate==0.8.9
    - tensorboard-data-server==0.6.1
    - termcolor==1.1.0
    - terminaltables==3.1.10
    - tokenizers==0.11.6
    - torchmetrics==0.7.2
    - transformers==4.18.0
    - ujson==4.2.0
    - wandb==0.12.10
    - yapf==0.31.0
    - yaspin==2.1.0
